function cleanperm = removeSubjfromPerm(perm,drop)
% Removes subjects from a Palm permtuation
%
% perm is a permutation matrix, as generated by Palm (N x 1)
% drop is a boolean vector (N x 1), saying which subjects should be dropped
% 
% Diego Vidaurre

[N,nperm] = size(perm);
if size(drop,1)>1, drop = drop'; end

badsubj = find(drop); 
if isempty(badsubj), 
    cleanperm = perm; 
    return; 
end

dictionary = NaN(N,1);
c = 1; 
for j = 1:N
    if ~any(j==badsubj)
        dictionary(j) = c; 
        c = c + 1; 
    end
end

cleanperm = zeros(N-length(badsubj),nperm);

for pe = 1:nperm
    % remove the indexes referred to bad subjects
    drop = false(N,1);
    for j = badsubj 
        drop(perm(:,pe)==j) = true;
    end
    p = perm(~drop,pe); 
    % adjust the indexes so that they refer to the cleaned list
    cleanperm(:,pe) = dictionary(p);    
end
    
end
